package org.videolan.libvlcrs.demo

import android.app.Activity
import android.content.Intent
import android.net.Uri
import android.os.Bundle
import android.widget.ArrayAdapter
import android.widget.Button
import android.widget.ListView
import android.widget.TextView
import org.videolan.libvlcrs.LibVLCRs
import java.io.File

/**
 * Launcher: lists the self-test media bundled in `assets/` (generated by CI) and
 * offers a document picker for the user's own files.
 *
 * Bundled clips are copied to the cache directory on first use so that the
 * engine opens them through a real file path — that also exercises the container
 * prober, which needs a seekable source to read the spherical metadata.
 */
class MainActivity : Activity() {

    private data class Item(val label: String, val asset: String?, val uri: Uri?)

    private val items = mutableListOf<Item>()
    private lateinit var status: TextView
    private lateinit var progress: TextView

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        status = findViewById(R.id.status)
        progress = findViewById(R.id.progress)
        val list = findViewById<ListView>(R.id.media_list)
        val openButton = findViewById<Button>(R.id.open_document)

        status.text = describeEngine()

        items.clear()
        items.add(Item("Open a file… (SAF)", null, null))
        for (name in bundledMedia()) {
            items.add(Item("asset: $name", name, null))
        }
        if (items.size == 1) {
            items.add(Item("no bundled test media found", null, null))
        }

        list.adapter = ArrayAdapter(
            this,
            android.R.layout.simple_list_item_1,
            items.map { it.label }
        )
        list.setOnItemClickListener { _, _, position, _ ->
            val item = items.getOrNull(position) ?: return@setOnItemClickListener
            when {
                item.asset == null && item.uri == null -> pickDocument()
                item.asset != null -> openAsset(item.asset)
                else -> startPlayer(uri = item.uri.toString())
            }
        }
        openButton.setOnClickListener { pickDocument() }
    }

    private fun describeEngine(): String {
        val supported = LibVLCRs.isSupported(this)
        val version = if (supported) runCatching { LibVLCRs.version() }.getOrDefault("?") else "n/a"
        return buildString {
            append("libvlcrs ").append(version).append('\n')
            append("device: ").append(android.os.Build.MANUFACTURER).append(' ')
                .append(android.os.Build.MODEL).append('\n')
            append("abi: ").append(android.os.Build.SUPPORTED_ABIS.joinToString())
                .append("  api: ").append(android.os.Build.VERSION.SDK_INT).append('\n')
            if (!supported) {
                append("⚠ this device is not supported: libvlcrs needs arm64-v8a and API 26+")
            } else {
                append("engine: Rust core + platform MediaCodec/AAudio, arm64-v8a release")
            }
        }
    }

    private fun bundledMedia(): List<String> {
        val extensions = setOf("mp4", "mkv", "webm", "mov", "m4v")
        return runCatching { assets.list("") }
            .getOrNull()
            ?.filter { name -> extensions.contains(name.substringAfterLast('.', "").lowercase()) }
            ?.sorted()
            ?: emptyList()
    }

    private fun pickDocument() {
        val intent = Intent(Intent.ACTION_OPEN_DOCUMENT).apply {
            addCategory(Intent.CATEGORY_OPENABLE)
            type = "video/*"
        }
        @Suppress("DEPRECATION")
        startActivityForResult(intent, REQUEST_OPEN_DOCUMENT)
    }

    @Deprecated("framework only: no androidx in this project")
    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        super.onActivityResult(requestCode, resultCode, data)
        if (requestCode == REQUEST_OPEN_DOCUMENT && resultCode == RESULT_OK) {
            val uri = data?.data ?: return
            runCatching {
                contentResolver.takePersistableUriPermission(
                    uri, Intent.FLAG_GRANT_READ_URI_PERMISSION
                )
            }
            startPlayer(uri = uri.toString())
        }
    }

    /** Copy a bundled clip into the cache and play it from a real path. */
    private fun openAsset(name: String) {
        progress.text = "copying $name…"
        Thread {
            val result = runCatching {
                val target = File(cacheDir, name)
                val expected = runCatching {
                    assets.openFd(name).use { it.length }
                }.getOrDefault(-1L)
                if (!target.exists() || (expected > 0 && target.length() != expected)) {
                    assets.open(name).use { input ->
                        target.outputStream().use { output -> input.copyTo(output) }
                    }
                }
                target.absolutePath
            }
            runOnUiThread {
                progress.text = ""
                result.fold(
                    onSuccess = { path -> startPlayer(path = path) },
                    onFailure = { t -> progress.text = "cannot prepare $name: ${t.message}" }
                )
            }
        }.start()
    }

    private fun startPlayer(path: String? = null, uri: String? = null) {
        val intent = Intent(this, PlayerActivity::class.java)
        if (path != null) intent.putExtra(PlayerActivity.EXTRA_PATH, path)
        if (uri != null) intent.putExtra(PlayerActivity.EXTRA_URI, uri)
        startActivity(intent)
    }

    private companion object {
        const val REQUEST_OPEN_DOCUMENT = 1001
    }
}
